InsightHub/InsightHub.Web/Areas/Admin/Controllers/BannedUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsightHub.Data;
using InsightHub.Data.Entities;
using InsightHub.Services.Contracts;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace InsightHub.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BannedUsersController : Controller
    {
        private readonly IUserServices _userServices;

        public BannedUsersController(IUserServices userServices)
        {
            _userServices = userServices;
        }

        /// <summary>
        /// Get All Banned Users
        /// </summary>
        /// <param name="search">The string to search for</param>
        /// <param name="pageNumber">The int for a page number</param>
        ///<returns>On success - View with banned users(in a paged list). </returns>
        /// <response code="200">Returns All Banned Users(in a paged list).</response>
        // GET: Admin/BannedUsers
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public async Task<IActionResult> Index(string search, int? pageNumber)
        {
            var users = await _userServices.GetBannedUsers(search);
            ViewData["ResultsCount"] = users.Count;
            ViewData["Search"] = search;
            if (search != null)
            {
                pageNumber = 1;
            }
            int pageSize = 10;
            return View(await users.ToPagedListAsync(pageNumber ?? 1, pageSize));
        }

        /// <summary>
        /// Unban an existing user(load form view) 
        /// </summary>
        /// <param name="id">The id of the user</param>
        /// <returns>On success - load Unban form view.</returns>
        /// <response code="200">Load Unban form view.</response>
        /// <response code="404">If id or user is null - NotFound</response>
        // GET: Admin/BannedUsers/Unban/5
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Unban(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userServices.GetUser(id.Value);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        /// <summary>
        /// Unban an existing user
        /// </summary>
        /// <param name="id">The id of the user.</param>
        /// <returns>On success - Redirect to Index view</returns>
        /// <response code="308">Redirect to Index view.</response>
        // POST: Admin/BannedUsers/Unban/5
        [ProducesResponseType(StatusCodes.Status200OK)]
        [HttpPost, ActionName("Unban")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UnbanConfirmed(int id)
        {
            await _userServices.UnbanUser(id);
            return RedirectToAction("Index");
        }
    }
}

InsightHub/InsightHub.Web/Areas/Admin/Controllers/PendingUsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsightHub.Data;
using InsightHub.Data.Entities;
using InsightHub.Services.Contracts;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace InsightHub.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PendingUsersController : Controller
    {
        private readonly IUserServices _userServices;

        public PendingUsersController(IUserServices userServices)
        {
            _userServices = userServices;
        }
        /// <summary>
        /// Get All Pending Users
        /// </summary>
        /// <param name="search">The string to search for</param>
        /// <param name="pageNumber">The int for a page number</param>
        ///<returns>On success - View with users(in a paged list). </returns>
        /// <response code="200">Returns All Pending Users(in a paged list).</response>
        // GET: Admin/PendingUsers
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public async Task<IActionResult> Index(string search, int? pageNumber)
        {
            var users = await _userServices.GetPendingUsers(search);
            ViewData["Search"] = search;
            ViewData["ResultsCount"] = users.Count;
            if (search != null)
            {
                pageNumber = 1;
            }
            int pageSize = 10;
            return View(await users.ToPagedListAsync(pageNumber ?? 1, pageSize));
        }
        /// <summary>
        /// Aprove user
        /// </summary>
        /// <param name="id">The id of the user.</param>
        /// <returns>On success - Redirect to Index View</returns>
        /// <response code="308">Approved - Redirect To Index View.</response>
        /// <response code="404">If id is null - NotFound</response>
        // Get: Admin/PendingUsers/Approve/5
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status308PermanentRedirect)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Approve(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            await _userServices.ApproveUser(id.Value);

            return RedirectToAction(nameof(Index));
        }
    }
}

InsightHub/InsightHub.Web/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsightHub.Data;
using InsightHub.Data.Entities;
using InsightHub.Services.Contracts;
using InsightHub.Models;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.Linq.Expressions;
using Microsoft.Data.SqlClient;

namespace InsightHub.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly IUserServices _userServices;

        public UsersController(IUserServices userServices)
        {
            _userServices = userServices;
        }
        /// <summary>
        /// Get All Users
        /// </summary>
        /// <param name="search">The string to search for</param>
        /// <param name="pageNumber">The int for a page number</param>
        ///<returns>On success - View with users(in a paged list). </returns>
        /// <response code="200">Returns All Users(in a paged list).</response>
        // GET: Admin/Users
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public async Task<IActionResult> Index(string search, int? pageNumber)
        {
            var users = await _userServices.GetUsers(search);
            ViewData["ResultsCount"] = users.Count();
            if(search != null)
            {
                pageNumber = 1;
            }
            int pageSize = 10;
            return View(await users.ToPagedListAsync(pageNumber ?? 1, pageSize));
        }

        /// <summary>
        /// Gets Details View of certain User
        /// </summary>
        /// <param name="id">The id of the certain user</param>
        /// <returns>On success - View of certain user's Details</returns>
        /// <response code="200">Returns View of certain user's Details.</response>
        /// <response code="404">If id or the user is null - NotFound.</response>
        // GET: Admin/Users/Details/5
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userServices.GetUser(id.Value);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        /// <summary>
        /// Edit an existring user(load form view) 
        /// </summary>
        /// <param name="id">The id of the edited user</param>
        /// <returns>On success - load Edit form view.</returns>
        /// <response code="200">Load Edit form view.</response>
        /// <response code="404">If id or user is null - NotFound</response>
        // GET: Admin/Users/Edit/5
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userServices.GetUser(id.Value);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        /// <summary>
        /// Edit an existing User
        /// </summary>
        /// <param name="industry">User to Bind</param>
        /// <returns>On success - Redirect to IndexView
        /// If ModelState is not true, load same page.
        /// If id is not the same - NotFound()</returns>
        /// <response code="308">Edited - redirected to IndexView.</response>
        /// <response code="404">Not edited - NotFound.</response>
        // POST: Users/Edit/2
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status308PermanentRedirect)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FirstName,LastName,IsPending,CreatedOn,ModifiedOn,IsBanned,BanReason,Id")] UserModel userModel)
        {
            if (id != userModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _userServices.UpdateUser(id, userModel.FirstName, userModel.LastName, userModel.IsBanned, userModel.BanReason);
                return RedirectToAction(nameof(Index));
            }
            return View(userModel);
        }


        /// <summary>
        /// Delete an existring user (load form view)
        /// </summary>
        /// <param name="id">The id of the edited user</param>
        /// <returns>On success - load Edit form view.</returns>
        /// <response code="200">Load Delete form view.</response>
        /// <response code="404">If id or user is null - NotFound</response>
        // GET: Admin/Users/Delete/5
        [Authorize(Roles = "Admin")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userServices.GetUser(id.Value);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        /// <summary>
        /// Delete an existing user
        /// </summary>
        /// <param name="id">The id of the deleted user.</param>
        /// <returns>On success - Redirect to Index view</returns>
        /// <response code="308">Redirect to Index view</response>
        // POST: Admin/Users/Delete/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _userServices.DeleteUser(id);
                return RedirectToAction(nameof(Index));
            }
            catch(DbUpdateException)
            {
                throw new ArgumentException("Unable to Delete Author while they still have Reports in the Database.");
            }
        }

        /// <summary>
        /// Ban an existring user (load form view)
        /// </summary>
        /// <param name="id">The id of the banned user</param>
        /// <returns>On success - load Edit form view.</returns>
        /// <response code="200">Load Delete form view.</response>
        /// <response code="404">If id or user is null - NotFound</response>
        // GET: Admin/Users/Ban/5
        [Authorize(Roles = "Admin")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Ban(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var user = await _userServices.GetUser(id.Value);
            if(user == null)
            {
                return NotFound();
            }
            return View(user);
        }
        /// <summary>
        /// Ban an existing user
        /// </summary>
        /// <param name="id">The id of the banned user.</param>
        /// <returns>On success - Redirect to Index view</returns>
        /// <response code="308">Redirect to Index view</response>
        // POST: Admin/Users/Ban/5
        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Ban")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> BanConfirmed(int id, string banReason)
        {
            await _userServices.BanUser(id, banReason);
            return RedirectToAction("Index");
        }
    }
}

InsightHub/InsightHub.Web/Areas/Admin/Views/Users/Ban.cshtml
@model InsightHub.Models.UserModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="display-4" style="color:#04202C; font-family: Cambria">
    Ban @Html.DisplayFor(model => model.Email)
</h2>

<h4 class="font-italic">Are you sure you want to ban this user?</h4>
<div>
    <form asp-action="Ban">
        <div class="form-group">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <label asp-for="BanReason" class="control-label"></label>
            <input asp-for="BanReason" class="form-control" />
            <span asp-validation-for="BanReason" class="text-danger"></span>
        </div>
        <input type="hidden" asp-for="Id" />
        <div class="form-group">
            <input type="submit" value="Ban" class="btn btn-outline-danger" />
        </div>
    </form>
</div>

InsightHub/InsightHub.Web/Areas/Admin/Views/Users/Delete.cshtml
@model InsightHub.Models.UserModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a class="btn btn-outline-dark" asp-action="Index">Back to List</a>
<h2 class="display-4" style="color:#04202C; font-family: Cambria">
    Delete
</h2>

<h4 class="font-italic">Are you sure you want to delete this?</h4>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            Registered On
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
    </dl>

    <form asp-controller="Users" asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-outline-danger" /> <br />
    </form>
</div>

InsightHub/InsightHub.Web/Areas/Admin/Views/Users/Details.cshtml
@model InsightHub.Models.UserModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a class="btn btn-outline-dark" asp-action="Index">Back to List</a>
<h1 class="display-4" style="color:#04202C; font-family: Cambria">
    Details
</h1>

<div>
    <h3>
        User:&nbsp;@Html.DisplayFor(model => model.Email)
    </h3>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsPending)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsPending)
        </dd>
        <dt class="col-sm-2">
            Registered On
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ModifiedOn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ModifiedOn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsBanned)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsBanned)
        </dd>
        @if (Model.IsBanned)
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.BanReason)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.BanReason)
            </dd>
        }
    </dl>
</div>
<div>
    <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <text>
        &nbsp;
    </text>
    @if (Model.IsPending)
    {
        <a class="btn btn-outline-success" asp-area="Admin" asp-controller="PendingUsers" asp-action="Approve" asp-route-id="@Model.Id">Approve</a>
        <text>
            &nbsp;
        </text>
    }
    @if (Model.IsBanned)
    {
        <a class="btn btn-outline-success" asp-area="Admin" asp-controller="BannedUsers" asp-action="Unban" asp-route-id="@Model.Id">Unban</a>
        <text>
            &nbsp;
        </text>
    }
    @if (!Model.IsBanned)
    {
        <a class="btn btn-outline-warning" asp-area="Admin" asp-controller="Users" asp-action="Ban" asp-route-id="@Model.Id">Ban</a>
        <text>
            &nbsp;
        </text>
    }
    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
</div>

InsightHub/InsightHub.Web/Areas/Admin/Views/Users/Edit.cshtml
@model InsightHub.Models.UserModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <a class="btn btn-outline-dark" asp-action="Index">Back to List</a>
</div>

<h2 class="display-4" style="color:#04202C; font-family: Cambria">
    Edit
</h2>

<h4>
    User:&nbsp;@Html.DisplayFor(model => model.Email)
</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-outline-dark" />
            </div>
        </form>
    </div>
</div>

InsightHub/InsightHub.Web/Areas/Admin/Views/Users/Index.cshtml
@model X.PagedList.StaticPagedList<InsightHub.Models.UserModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-4" style="color:#04202C; font-family: Cambria">
    <b>
        Users
    </b>
</h1>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Search Users: <input type="text" name="search" value="@ViewData["Search"]" />
            <input type="submit" value="Search" class="btn btn-outline-dark" />
            <br />
            @ViewData["ResultsCount"] result(s)
        </p>
    </div>
</form>
@if (Model.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Registered On
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FirstName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LastName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedOn)
                        </td>
                        <td>
                            <a class="btn btn-outline-dark" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <text>
                                &nbsp;
                            </text>
                            <a class="btn btn-outline-warning" asp-action="Ban" asp-route-id="@item.Id">Ban</a>
                            <text>
                                &nbsp;
                            </text>
                            <a class="btn btn-outline-dark" asp-action="Details" asp-route-id="@item.Id">Details</a>
                            <text>
                                &nbsp;
                            </text>
                            <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="font-italic">No users found.</tr>
            }
        </tbody>
    </table>
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";

    <p class="text-dark">
        <a asp-action="Index"
           asp-route-sort="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageNumber - 1)"
           asp-route-search="@ViewData["Search"]"
           class="btn btn-outline-dark @prevDisabled">
            Previous
        </a>
        &nbsp;@(ViewData["PageNumber"] ?? 1)&nbsp;
        <a asp-action="Index"
           asp-route-sort="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageNumber + 1)"
           asp-route-search="@ViewData["Search"]"
           class="btn btn-outline-dark @nextDisabled">
            Next
        </a>
    </p>
}
else
{
    <h4 class="font-italic">No active users.</h4>
}