InsightHub/InsightHub.Web/Areas/Admin/Controllers/PendingReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsightHub.Data;
using InsightHub.Data.Entities;
using System.Security.Claims;
using InsightHub.Services.Contracts;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;

namespace InsightHub.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PendingReportsController : Controller
    {
        private readonly IReportServices _reportServices;
        private readonly IUserServices _userServices;
        private readonly IEmailSenderServices _emailSenderServices;

        public PendingReportsController(IReportServices reportServices, IUserServices userServices, IEmailSenderServices emailSenderServices)
        {
            _reportServices = reportServices ?? throw new ArgumentNullException("ReportServices can NOT be null");
            _userServices = userServices ?? throw new ArgumentNullException("UserServices can NOT be null");
            _emailSenderServices = emailSenderServices ?? throw new ArgumentNullException("EmailSenderServices can NOT be null");
        }

        /// <summary>
        /// Get All Pending Reports
        /// </summary>
        /// <param name="search">The string to search for</param>
        /// <param name="pageNumber">The int for a page number</param>
        ///<returns>On success - View with reports(in a paged list). </returns>
        /// <response code="200">Returns All Pending Reports(in a paged list).</response>
        // GET: Admin/PendingReports/5
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public async Task<IActionResult> Index(string sort, string search, int? pageNumber)
        {

            ViewData["CurrentSort"] = sort;
            ViewData["SortByTitle"] = sort == "title" ? "title_desc" : "title";
            ViewData["SortByAuthor"] = sort == "author" ? "author_desc" : "author";
            ViewData["SortByIndustry"] = sort == "industry" ? "industry_desc" : "industry";
            ViewData["SortByDate"] = sort == "newest" ? "oldest" : "newest";
            ViewData["SortByDownloads"] = sort == "downloads" ? "downloads_asc" : "downloads";

            if (search != null)
            {
                pageNumber = 1;
            }

            ViewData["Search"] = search;

            var reports = await _reportServices.GetPendingReports(sort, search);

            ViewData["ResultsCount"] = reports.Count;

            var pageSize = 8;
            return View(await reports.ToPagedListAsync(pageNumber ?? 1, pageSize));
        }
        /// <summary>
        /// Aprove report
        /// </summary>
        /// <param name="id">The id of the report.</param>
        /// <returns>On success - Redirect to Index View</returns>
        /// <response code="308">Approved - Redirect To Index View.</response>
        /// <response code="404">If id is null - NotFound</response>
        // GET: Admin/PendingReports/Approve/5
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status308PermanentRedirect)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Approve(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var report = await _reportServices.GetReport(id.Value);
            if (report == null)
            {
                return NotFound();
            }
            await _reportServices.ApproveReport(id.Value);
            var subscribedEmails = await _userServices.GetSubscribedUsers(report.Industry);
            if (subscribedEmails.Length > 0)
            {
                _emailSenderServices.AutoSendMail(subscribedEmails);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

InsightHub/InsightHub.Web/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InsightHub.Data;
using InsightHub.Data.Entities;
using InsightHub.Services.Contracts;
using InsightHub.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.CodeAnalysis;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace InsightHub.Web.Controllers
{
    public class ReportsController : Controller
    {
        private readonly IReportServices _reportServices;
        private readonly IBlobServices _blobServices;
        private readonly IUserServices _userServices;
        private readonly IIndustryServices _industryServices;

        public ReportsController(IReportServices reportServices, IBlobServices blobServices, IUserServices userServices, IIndustryServices industryServices)
        {
            _reportServices = reportServices;
            _blobServices = blobServices;
            _userServices = userServices;
            _industryServices = industryServices;
        }

        /// <summary>
        /// Get all Reports
        /// </summary>
        /// <param name="sort">A string to sort by.</param>
        /// <param name="search">A string to search for.</param>
        /// <param name="author">A string to filter by.</param>
        /// <param name="industry">A string to filter by.</param>
        /// <param name="tag">A string to filter by.</param>
        /// <param name="pageNumber">A int page number.</param>
        /// <returns>On success - View with reports(in a paged list). </returns>
        /// <response code="200">Returns All Reports(in a paged list).</response>
        // GET: Reports
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public async Task<IActionResult> Index(string sort, string search, string author, string industry, string tag, int? pageNumber)
        {
            ViewData["CurrentSort"] = sort;
            ViewData["SortByTitle"] = sort == "title" ? "title_desc" : "title";
            ViewData["SortByAuthor"] = sort == "author" ? "author_desc" : "author";
            ViewData["SortByIndustry"] = sort == "industry" ? "industry_desc" : "industry";
            ViewData["SortByDate"] = sort == "newest" ? "oldest" : "newest";
            ViewData["SortByDownloads"] = sort == "downloads" ? "downloads_asc" : "downloads";
            ViewData["PageNumber"] = pageNumber;
            ViewData["Search"] = search;
            ViewData["Industry"] = industry;
            ViewData["Tag"] = tag;
            ViewData["Author"] = author;

            var reports = await _reportServices.GetReports(sort, search, author, industry, tag);
            ViewData["ResultsCount"] = reports.Count;

            int pageSize = 8;
            return View(await reports.ToPagedListAsync(pageNumber ?? 1, pageSize));
        }

        /// <summary>
        /// Gets Details View of certain Report
        /// </summary>
        /// <param name="id">The id of the certain report</param>
        /// <returns>On success - View of certain report's Details</returns>
        /// <response code="200">Returns View of certain report's Details.</response>
        /// <response code="404">If id or the report is null - NotFound.</response>
        // GET: Reports/Details/5
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound("Id can NOT be null");

            var report = await _reportServices.GetReport(id.Value);
            if (report == null)
                return NotFound("Report not found.");

            ViewData["Tags"] = report.Tags.Split(',').Select(t => t.Trim());

            return View(report);
        }
        /// <summary>
        /// Download a Report's content
        /// </summary>
        /// <param name="id">The id of the Report</param>
        /// <returns>On success - A Report's File
        /// If the Report does not exists - Throws Argument Null Exception</returns>
        /// <response code="200">Returns an Report's File</response>
        /// <response code="404">If id or report is null - NotFound</response>
        // GET: Reports/5/download
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [Authorize(Roles = "Admin, Client")]
        public async Task<IActionResult> Download(int? id)
        {
            if (id == null)
                return NotFound("Report not found.");
            var report = await _reportServices.GetReport(id.Value);
            if (report == null)
                return NotFound("Report not found.");
            var userId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            await _reportServices.AddToDownloadsCount(userId, id.Value);
            var data = await _blobServices.GetBlobAsync($"{report.Id}.pdf");
            return File(data.Content, "application/pdf", $"{report.Title}.pdf");
        }

        /// <summary>
        /// Load the Create View
        /// </summary>
        /// <returns>On success - form view</returns>
        // GET: Reports/Create
        [Authorize(Roles = "Admin, Author")]
        public async Task<IActionResult> Create()
        {
            var userId = Convert.ToInt32(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var user = await _userServices.GetUser(userId);
            var industries = await _industryServices.GetAllIndustries(null, null);
            ViewData["Industry"] = new SelectList(industries.Select(i => i.Name));
            ViewData["Author"] = user.Email;
            return View();
        }

        /// <summary>
        /// Create a new Report
        /// </summary>
        /// <param name="report">Report to Bind</param>
        /// <returns>On success - Redirect to IndexView
        /// If ModelState is not true, load same page.</returns>
        /// <response code="308">Created - redirected to IndexView.</response>
        /// <response code="204">Not created - same view.</response>
        // POST: Reports/Create
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status308PermanentRedirect)]
        [ProducesResponseType(StatusCodes.Status204NoContent)]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Summary,Description,Author,ImgUrl,Industry,Tags")] ReportModel report, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                //Validate File Exists
                if (file == null)
                {
                    throw new ArgumentException("Please upload a file.");
                }

                //Validate File Extension
                else
                {
                    string[] permittedExtensions = { ".pdf" };


                    var ext = Path.GetExtension(file.FileName).ToLowerInvariant();

                    if (string.IsNullOrEmpty(ext) || !permittedExtensions.Contains(ext))
                    {
                        throw new ArgumentException("Invalid file format. Please provide a PDF.");
                    }
                }
                
                //Create Report
                await _reportServices.CreateReport(report.Title, report.Summary, report.Description, report.Author, report.ImgUrl, report.Industry, report.Tags);

                //Get New Report ID
                var reportId = await _reportServices.GetReportsCount();
                //Upload Report File to Blob
                using (var stream = file.OpenReadStream())
                {
                    await _blobServices.UploadFileBlobAsync(stream, $"{reportId}.pdf");
                }
                return RedirectToAction("ReportPending", "Home");
            }

            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Edit an existring report(load form view) 
        /// </summary>
        /// <param name="id">The id of the edited report</param>
        /// <returns>On success - load Edit form view.</returns>
        /// <response code="200">Load Edit form view.</response>
        /// <response code="404">If id or report is null - NotFound</response>
        // GET: Reports/Edit/5
        [HttpGet]
        [ProducesResponseType(StatusCodes.Status200OK)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [Authorize(Roles = "Admin, Author")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound("Id can NOT be null");

            var report = await _reportServices.GetReport(id.Value);

            if (report == null)
                return NotFound("Report not found.");

            var industries = await _industryServices.GetAllIndustries(null, null);
            ViewData["Industry"] = new SelectList(industries.Select(i => i.Name));

            return View(report);
        }

        /// <summary>
        /// Edit an existing Report
        /// </summary>
        /// <param name="industry">Report to Bind</param>
        /// <returns>On success - Redirect to IndexView
        /// If ModelState is not true, load same page.
        /// If id is not the same - NotFound()</returns>
        /// <response code="308">Edited - redirected to IndexView.</response>
        /// <response code="404">Not edited - NotFound.</response>
        // POST: Reports/Edit/2
        [HttpPost]
        [ProducesResponseType(StatusCodes.Status308PermanentRedirect)]
        [ProducesResponseType(StatusCodes.Status404NotFound)]
        [ValidateAntiForgeryToken]

InsightHub/InsightHub.Web/Areas/Admin/Views/PendingReports/Index.cshtml
@model X.PagedList.StaticPagedList<InsightHub.Models.ReportModel>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <a class="btn btn-outline-dark" asp-action="Index">Back to Full List</a>

    <h1 style="color:#04202C; font-family: Cambria">Pending Reports</h1>

    <form asp-action="Index" method="get">
        <div class="form-actions">

            Search Reports: <input type="text" name="search" value="@ViewData["Search"]" />
            <input type="submit" value="Search" class="btn btn-outline-dark" />
            @ViewData["ResultsCount"] result(s)

            <p class="d-inline-block">
                <div class="dropdown float-right">
                    <button class="d-inline-flex btn btn-outline-dark dropdown-toggle" type="button" data-toggle="dropdown">
                        Sort By
                    </button>
                    <ul class="dropdown-menu text-white" style="background-color: #304040">
                        <li class="nav-item btn-outline-dark" style="padding-left:10px">
                            <a class="text-white" asp-action="Index" asp-route-sort="@ViewData["SortByTitle"]"
                               asp-route-search="@ViewData["Search"]">Title</a>
                        </li>
                        <li class="nav-item btn-outline-dark" style="padding-left:10px">
                            <a class="text-white" asp-action="Index" asp-route-sort="@ViewData["SortByAuthor"]"
                               asp-route-search="@ViewData["Search"]">Author</a>
                        </li>
                        <li class="nav-item btn-outline-dark" style="padding-left:10px">
                            <a class="text-white" asp-action="Index" asp-route-sort="@ViewData["SortByIndustry"]"
                               asp-route-search="@ViewData["Search"]">Industry</a>
                        </li>
                        <li class="nav-item btn-outline-dark" style="padding-left:10px">
                            <a class="text-white" asp-action="Index" asp-route-sort="@ViewData["SortByDate"]"
                               asp-route-search="@ViewData["Search"]">Date</a>
                        </li>
                        <li class="nav-item btn-outline-dark" style="padding-left:10px">
                            <a class="text-white" asp-action="Index" asp-route-sort="@ViewData["SortByDownloads"]"
                               asp-route-search="@ViewData["Search"]">Downloads</a>
                        </li>
                    </ul>
                </div>
            </p>
        </div>
    </form>
    <hr />

    <div class="row text-center">

        @if (Model.Count() > 0)
        {
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-md-6 mb-4">
                    <div class="card h-100 mw-100" style="background-color: #0a4863">
                        <img class="card-img-top" src="@Html.DisplayFor(modelItem => item.ImgUrl)" width="500" height="200" alt="">
                        <div class="card-body text-white">
                            <div class="row">
                                <div class="col-6 float-left">
                                    <a class="text-white" asp-area="" asp-controller="Reports" asp-action="Index" asp-route-industry=@item.Industry>
                                        @item.Industry
                                    </a>
                                </div>
                                <div class="col-6 float-right" style="color:#C9D1C8">
                                    @item.CreatedOn.ToShortDateString()
                                </div>
                            </div>
                            <row class="d-inline-block text-center">
                                <h5>
                                    <b>
                                        <a class="text-white font-weight-bold" style="font-family: Cambria"
                                           asp-area=""
                                           asp-controller="Reports"
                                           asp-action="Details"
                                           asp-route-id="@item.Id">@Html.DisplayFor(modelItem => item.Title)</a>
                                    </b>
                                </h5>
                            </row>
                            <div class="row text-left" style="color:#C9D1C8">
                                @Html.DisplayFor(modelItem => item.Summary)
                            </div>
                        </div>
                        <div class="card-footer">
                            <p class="row text-left" style="color:#C9D1C8">
                                By:&nbsp;
                                <a class="text-white" asp-area="" asp-controller="Reports" asp-action="Index" asp-route-author=@item.Author.Split(' ').Last()>
                                    @item.Author.Substring(0, item.Author.Substring(0, item.Author.Length - 1).LastIndexOf("- "))
                                </a>
                            </p>
                            <p class="row text-left" style="color:#C9D1C8">
                                Downloaded @Html.DisplayFor(modelItem => item.DownloadsCount) times
                            </p>
                            <a class="btn btn-outline-success" asp-action="Approve" asp-route-id="@item.Id">Approve</a>
                            <a class="btn btn-outline-light" asp-area="" asp-controller="Reports" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            <a class="btn btn-outline-danger" asp-area="" asp-controller="Reports" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </div>
                    </div>
                </div>
            }
        }
        else
        {
            <h4 class="font-italic">No pending reports found.</h4>
        }
    </div>
    <hr />
    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }
    <p class="text-dark">
        <a asp-action="Index"
           asp-route-sort="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageNumber - 1)"
           asp-route-search="@ViewData["Search"]"
           class="btn btn-outline-dark @prevDisabled">
            Previous
        </a>
        &nbsp;@(ViewData["PageNumber"] ?? 1)&nbsp;
        <a asp-action="Index"
           asp-route-sort="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageNumber + 1)"
           asp-route-search="@ViewData["Search"]"
           class="btn btn-outline-dark @nextDisabled">
            Next
        </a>
    </p>
</div>